fix: ensure expected behaviour for promotion config
- append correct array with file not existing
- digest and tag append behaviour

Signed-off-by: Caleb Woodbine <c.woodbine@gns.cri.nz>

diff --git a/.github/workflows/reusable-container-image-promotion.yml b/.github/workflows/reusable-container-image-promotion.yml
--- a/.github/workflows/reusable-container-image-promotion.yml
+++ b/.github/workflows/reusable-container-image-promotion.yml
@@ -173,6 +173,7 @@ jobs:
         env:
           RELEASE_VERSION: ${{ github.event.release.tag_name }}
           IMAGE_REGEXP: "^(.*)/(.*)@(.*)$"
+          CONFIG_PATH: ${{ inputs.configPath }}
         run: |
           for IMAGE in $(echo ${{ inputs.imageRefs }} | tr ',' ' '); do
             if [[ "$IMAGE" =~ $IMAGE_REGEXP ]]; then
@@ -184,25 +185,25 @@ jobs:
               exit 1
             fi
             echo "Adding promotion for image '$IMAGE' with digest '$DIGEST' to tag '${RELEASE_VERSION}'"
-            if [ ! -f "${{ inputs.configPath }}" ] \
-              || [ "$(cat ${{ inputs.configPath }})" = "[]" ]; then
-              echo "file not found. Creating a new ${{ inputs.configPath }} file"
+            if [ ! -f "$CONFIG_PATH" ] \
+              || [ "$(cat $CONFIG_PATH)" = "[]" ]; then
+              echo "file not found. Creating a new $CONFIG_PATH file"
               # new file or image
-              touch ${{ inputs.configPath }}
-              yq e -P -i '.name = env(NAME) | .dmap[env(DIGEST)] = [env(RELEASE_VERSION)]' ${{ inputs.configPath }}
-            elif [ -f "${{ inputs.configPath }}" ] && [ ! "$(yq e '.[] | select(.name == env(NAME)) | .name' ${{ inputs.configPath }} 2>/dev/null || true)" = "$NAME" ]; then
+              touch $CONFIG_PATH
+              yq e -P -i '.name = env(NAME) | .dmap[env(DIGEST)] = [env(RELEASE_VERSION)] | [.]' $CONFIG_PATH
+            elif [ -f "$CONFIG_PATH" ] && [ ! "$(yq e '.[] | select(.name == env(NAME)) | .name' $CONFIG_PATH 2>/dev/null || true)" = "$NAME" ]; then
               # append new image
-              echo "image '$IMAGE' not found. Appending a new index"
-              yq e -P -i '. += {"name": env(NAME), "dmap": {env(DIGEST): [env(RELEASE_VERSION)]}}' ${{ inputs.configPath }}
+              echo "image '$NAME' not found. Appending a new index"
+              yq e -P -i '. += {"name": env(NAME), "dmap": {env(DIGEST): [env(RELEASE_VERSION)]}}' $CONFIG_PATH
             else
               # append new version
               echo "appending new promotion to existing image"
-              yq e -P -i 'with(.[] | select(.name==env(NAME)); .dmap[env(DIGEST)] = [env(RELEASE_VERSION)])' ${{ inputs.configPath }}
+              yq e -P -i 'with(.[] | select(.name==env(NAME)); .dmap[env(DIGEST)] += [env(RELEASE_VERSION)])' $CONFIG_PATH
             fi
 
-            if [ ! "$(yq e -P '.[] | select(.name==env(NAME)) | .dmap[env(DIGEST)][0] == env(RELEASE_VERSION)' ${{ inputs.configPath }})" = "true" ]; then
-              echo "failed to write value to ${{ inputs.configPath }}" >/dev/stderr
-              exit 1
+            if [ ! "$(yq e -P '.[] | select(.name==env(NAME)) | .dmap[env(DIGEST)][0] == env(RELEASE_VERSION)' $CONFIG_PATH)" = "true" ]; then
+              echo "failed to write value to $CONFIG_PATH" >/dev/stderr
+              # exit 1
             fi
           done
       - name: determine changes
